output_dir: ./subsample_tlp_triplet_mlm_mtl_ckpt_1
tasks: [triplet, mlm]
theme_count: 2000
base_lr: 5.0e-5
train_args:
  num_epochs: 1
  batch_size: 32
  warmup_ratio: 0.06
  gradient_accumulation_steps: 8 
task_spec:
  dataset_name: upasanachatterjee/bignewsalign-with-gdelt
  themes_path: top_themes.txt
  max_triplet_samples: 1
  require_nonempty_themes_and_tone: True
loss_weights:
  triplet: 0.30
  themes: 2.45
  tone: 0.20
  mlm: 1.0