output_dir: ./subsample_tlp_story_ideo_mlm_mtl_ckpt_32_gpu_4090_48gb
tasks: [triplet_ideology, triplet_story, mlm, tone]
theme_count: 2000
tone_count: 1
base_lr: 5.0e-5
train_args:
  num_epochs: 1
  batch_size: 32
  warmup_ratio: 0.06
  log_every: 500
task_spec:
  dataset_name: upasanachatterjee/bignewsalign-with-gdelt
  themes_path: top_themes.txt
  max_triplet_samples: 16
  require_nonempty_themes_and_tone: True